# Generated by Django 4.1.3 on 2022-11-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('size', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
