# Generated by Django 4.1.3 on 2022-11-30 23:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=20)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('cover_image', models.ImageField(default=None, upload_to='cover_image/')),
                ('scene_image_1', models.ImageField(default=None, upload_to='cover_image/')),
                ('scene_image_2', models.ImageField(default=None, upload_to='cover_image/')),
                ('scene_image_3', models.ImageField(default=None, upload_to='cover_image/')),
                ('trailer_link', models.CharField(default=None, max_length=50)),
                ('movie_file_4k', models.FileField(default=None, upload_to='movie_file/')),
                ('movie_file_uhd', models.FileField(default=None, upload_to='movie_file/')),
            ],
        ),
    ]
