# Generated by Django 4.1.3 on 2022-11-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='scene_image_1',
            field=models.ImageField(default=None, upload_to='cover_image/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='scene_image_2',
            field=models.ImageField(default=None, upload_to='cover_image/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='scene_image_3',
            field=models.ImageField(default=None, upload_to='cover_image/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_link',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cover_image',
            field=models.ImageField(default=None, upload_to='cover_image/'),
        ),
    ]
