# Generated by Django 4.1.3 on 2022-11-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_movie_file_4k_movie_movie_file_uhd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='size',
        ),
    ]
