# Generated by Django 4.1.3 on 2022-11-28 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movie_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_file_UHD',
            new_name='movie_file_uhd',
        ),
    ]
